export const rows = [
  {
    id: 1,
    name: "Halem",
    email: "Halem@gmail.com",
    age: 36,
    phone: "01234567891",
    address: "12 cavie street,CD",
    city: "Tenting",
    zipCode: "14215",
    registerId: "19869",
  },
  {
    id: 2,
    name: "Ahmed",
    email: "Ahmed@gmail.com",
    age: 32,
    phone: "01234567891",
    address: "12 cavie street,CD",
    city: "Tenting",
    zipCode: "14915",
    registerId: "183569",
  },
  {
    id: 3,
    name: "Jak",
    email: "Jak@gmail.com",
    age: 40,
    phone: "01234567891",
    address: "12 cavie street,CD",
    city: "Tenting",
    zipCode: "14219",
    registerId: "123568",
  },
  {
    id: 4,
    name: "Malay",
    email: "Malay@gmail.com",
    age: 35,
    phone: "01234567891",
    address: "12 cavie street,CD",
    city: "Tenting",
    zipCode: "94215",
    registerId: "123869",
  },
  {
    id: 5,
    name: "Moly",
    email: "Malay@gmail.com",
    age: 33,
    phone: "01234567891",
    address: "12 cavie street,CD",
    city: "Tenting",
    zipCode: "14915",
    registerId: "123569",
  },
  {
    id: 6,
    name: "Karim",
    email: "Karim@gmail.com",
    age: 21,
    phone: "01234567891",
    address: "12 cavie street,CD",
    city: "Tenting",
    zipCode: "19215",
    registerId: "123869",
  },
  {
    id: 7,
    name: "Hnan",
    email: "Hnan@gmail.com",
    age: 31,
    phone: "01234567891",
    address: "12 cavie street,CD",
    city: "Tenting",
    zipCode: "914295",
    registerId: "123569",
  },
  {
    id: 8,
    name: "Titi",
    email: "Titi@gmail.com",
    age: 28,
    phone: "01234567891",
    address: "12 cavie street,CD",
    city: "Tenting",
    zipCode: "914919",
    registerId: "183869",
  },
  {
    id: 9,
    name: "Hesham",
    email: "Hesham@gmail.com",
    age: 23,
    phone: "01234567891",
    address: "12 cavie street,CD",
    city: "Tenting",
    zipCode: "919215",
    registerId: "12358",
  },
  {
    id: 10,
    name: "Hassnaa",
    email: "Hassnaa@gmail.com",
    age: 22,
    phone: "01234567891",
    address: "12 cavie street,CD",
    city: "Tenting",
    zipCode: "14915",
    registerId: "83569",
  },
];

export const columns = [
  {
    field: "id",
    headerName: "Id",
    width: 33,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "registerId",
    headerName: "Register Id",
    flex: 1,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "name",
    headerName: "Name",
    align: "center",
    headerAlign: "center",
  },
  {
    field: "email",
    headerName: "Email",
    flex: 1,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "age",
    headerName: "Age",
    align: "center",
    headerAlign: "center",
    width: 150,
  },
  {
    field: "phone",
    headerName: "Phone",
    flex: 1,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "address",
    headerName: "Address",
    flex: 1,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "city",
    headerName: "City",
    flex: 1,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "zipCode",
    headerName: "zipCode",
    flex: 1,
    align: "center",
    headerAlign: "center",
  },
];
